# Generated by cloudnative-pg-timescaledb/scripts/generate-bake.sh
# Story 1.5 skeleton only; executable Bake behavior is owned by Story 3.3.
group "default" {
  targets = [
    "pg17-trixie",
    "pg18-trixie",
    "pg19beta1-trixie",
    "pg17-bookworm",
    "pg18-bookworm",
    "pg19beta1-bookworm",
  ]
}

target "pg17-trixie" {
  context = "."
  dockerfile = "cloudnative-pg-timescaledb/generated/17/trixie/Dockerfile"
  platforms = ["linux/amd64", "linux/arm64"]
  tags = ["local/pg17-trixie:skeleton"]
  labels = {
    "org.opencontainers.image.version" = "17"
    "io.pnet.debian-variant" = "trixie"
    "io.pnet.publish" = "false"
  }
}

target "pg18-trixie" {
  context = "."
  dockerfile = "cloudnative-pg-timescaledb/generated/18/trixie/Dockerfile"
  platforms = ["linux/amd64", "linux/arm64"]
  tags = ["local/pg18-trixie:skeleton"]
  labels = {
    "org.opencontainers.image.version" = "18"
    "io.pnet.debian-variant" = "trixie"
    "io.pnet.publish" = "false"
  }
}

target "pg19beta1-trixie" {
  context = "."
  dockerfile = "cloudnative-pg-timescaledb/generated/19beta1/trixie/Dockerfile"
  platforms = ["linux/amd64", "linux/arm64"]
  tags = ["local/pg19beta1-trixie:skeleton"]
  labels = {
    "org.opencontainers.image.version" = "19beta1"
    "io.pnet.debian-variant" = "trixie"
    "io.pnet.publish" = "false"
  }
}

target "pg17-bookworm" {
  context = "."
  dockerfile = "cloudnative-pg-timescaledb/generated/17/bookworm/Dockerfile"
  platforms = ["linux/amd64", "linux/arm64"]
  tags = ["local/pg17-bookworm:skeleton"]
  labels = {
    "org.opencontainers.image.version" = "17"
    "io.pnet.debian-variant" = "bookworm"
    "io.pnet.publish" = "false"
  }
}

target "pg18-bookworm" {
  context = "."
  dockerfile = "cloudnative-pg-timescaledb/generated/18/bookworm/Dockerfile"
  platforms = ["linux/amd64", "linux/arm64"]
  tags = ["local/pg18-bookworm:skeleton"]
  labels = {
    "org.opencontainers.image.version" = "18"
    "io.pnet.debian-variant" = "bookworm"
    "io.pnet.publish" = "false"
  }
}

target "pg19beta1-bookworm" {
  context = "."
  dockerfile = "cloudnative-pg-timescaledb/generated/19beta1/bookworm/Dockerfile"
  platforms = ["linux/amd64", "linux/arm64"]
  tags = ["local/pg19beta1-bookworm:skeleton"]
  labels = {
    "org.opencontainers.image.version" = "19beta1"
    "io.pnet.debian-variant" = "bookworm"
    "io.pnet.publish" = "false"
  }
}
