#!/usr/bin/env bash
set -Eeuo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../../../.." && pwd)"
FIXTURE_DIR="${ROOT_DIR}/cloudnative-pg-timescaledb/tests/docs/readme/fixtures"
METADATA="${ROOT_DIR}/cloudnative-pg-timescaledb/versions.yaml"
TABLE="${ROOT_DIR}/cloudnative-pg-timescaledb/docs/generated/compatibility-table.md"

diag() {
  printf 'command: %s\nartifact: %s\nexpected: %s\nactual: %s\nremediation: %s\n' "$@" >&2
}

validate_readme() {
  local readme="$1"
  local table="${2:-${TABLE}}"
  python3 - "${readme}" "${table}" "${METADATA}" <<'PY'
import re
import sys
from pathlib import Path

readme = Path(sys.argv[1])
table = Path(sys.argv[2])
metadata = Path(sys.argv[3])
command = f"validate-readme {readme}"

def fail(artifact, expected, actual, remediation):
    raise SystemExit(
        f"command: {command}\n"
        f"artifact: {artifact}\n"
        f"expected: {expected}\n"
        f"actual: {actual}\n"
        f"remediation: {remediation}"
    )

def require(pattern, expected, remediation, flags=re.I | re.S):
    if not re.search(pattern, text, flags):
        fail(readme, expected, "missing", remediation)

def reject(pattern, expected, remediation, flags=re.I | re.S):
    match = re.search(pattern, text, flags)
    if match:
        fail(readme, expected, match.group(0), remediation)

def reject_unless_negated(pattern, expected, remediation, flags=re.I | re.S):
    for match in re.finditer(pattern, text, flags):
        window = text[max(0, match.start() - 80):match.end()].lower()
        if re.search(r"\b(?:never|not|no|without|must\s+not|do\s+not|does\s+not)\b", window):
            continue
        fail(readme, expected, match.group(0), remediation)

def scalar(value):
    value = value.strip()
    if value.startswith('"') and value.endswith('"'):
        return value[1:-1]
    if value.startswith("'") and value.endswith("'"):
        return value[1:-1]
    if value in {"true", "false"}:
        return value == "true"
    if value.startswith("[") and value.endswith("]"):
        body = value[1:-1].strip()
        if not body:
            return []
        return [scalar(part.strip()) for part in body.split(",")]
    return value

def load_entries(path):
    entries = []
    current = None
    in_entries = False
    for raw in path.read_text().splitlines():
        if raw.startswith("entries:"):
            in_entries = True
            continue
        if not in_entries:
            continue
        if raw.startswith("  - "):
            if current is not None:
                entries.append(current)
            current = {}
            line = raw[4:]
            if ":" in line:
                key, value = line.split(":", 1)
                current[key.strip()] = scalar(value.strip())
            continue
        if current is not None and raw.startswith("    ") and ":" in raw:
            key, value = raw.strip().split(":", 1)
            current[key.strip()] = scalar(value.strip())
    if current is not None:
        entries.append(current)
    return entries

def render_table(entries):
    lines = [
        "# Generated Compatibility Table",
        "",
        "<!-- Generated by cloudnative-pg-timescaledb/scripts/generate-docs.sh from cloudnative-pg-timescaledb/versions.yaml. -->",
        "",
        "| PostgreSQL | Debian | Publish | Experimental | Latest Eligible | Platforms | Skip Reason |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for entry in entries:
        lines.append(
            "| {pg_major} | {debian_variant} | {publish} | {experimental} | {latest_eligible} | {platforms} | {skip_reason} |".format(
                pg_major=entry["pg_major"],
                debian_variant=entry["debian_variant"],
                publish=str(entry["publish"]).lower(),
                experimental=str(entry["experimental"]).lower(),
                latest_eligible=str(entry["latest_eligible"]).lower(),
                platforms=", ".join(entry["platforms"]),
                skip_reason=entry["skip_reason"],
            )
        )
    return "\n".join(lines) + "\n"

if not readme.exists():
    fail(readme, "README artifact exists", "missing", "Create the public README artifact required by Story 5.1.")
if not table.exists():
    fail(table, "generated compatibility-table.md exists", "missing", "Run make generate after adding the compatibility table generator.")

text = readme.read_text()
require(r"CloudNativePG-compatible PostgreSQL images?", "README explains CloudNativePG-compatible PostgreSQL image purpose", "Describe the public image family at overview level.")
require(r"ghcr\.io/pnetcloud/cloudnative-pg-timescaledb", "README documents the GHCR image namespace", "Document the GHCR repository users should pull from.")
for extension in ["TimescaleDB", "TimescaleDB Toolkit", "pgvector", "PGAudit"]:
    require(rf"\b{re.escape(extension)}\b", f"README names {extension}", "List the supported extension set.")
for pg in ["17", "18", "19beta1"]:
    require(rf"PostgreSQL\s+`?{re.escape(pg)}`?", f"README names PostgreSQL {pg}", "List every supported PostgreSQL major from versions.yaml.")
require(r"experimental\s+PostgreSQL\s+`?19beta1`?|PostgreSQL\s+`?19beta1`?\s+is\s+experimental", "PostgreSQL 19beta1 is marked experimental", "Mark PG19 beta as experimental wherever it appears.")
require(r"Debian\s+`?trixie`?.{0,80}primary\s+recommended\s+variant|primary\s+recommended\s+variant.{0,80}Debian\s+`?trixie`?", "Debian trixie is primary recommended", "State that trixie is the primary recommended Debian variant.")
require(r"Debian\s+`?bookworm`?.{0,80}secondary\s+variant|secondary\s+variant.{0,80}Debian\s+`?bookworm`?", "Debian bookworm is secondary", "State that bookworm is the secondary Debian variant.")
require(r"`latest`.{0,80}convenience-only|convenience-only.{0,80}`latest`", "latest is documented as convenience-only", "Do not present latest as the primary production tag.")
require(r"`latest`.{0,80}(?:points\s+to|targets).{0,80}PostgreSQL\s+`?18`?.{0,80}Debian\s+`?trixie`?", "latest points to PostgreSQL 18 on Debian trixie", "Keep latest aligned with current_major 18 and primary trixie metadata.")
require(r"CloudNativePG Barman Cloud Plugin", "README names CloudNativePG Barman Cloud Plugin path", "Document Barman support through the plugin path.")
require(r"legacy\s+in-image\s+`?barman-cloud`?.{0,120}(?:not\s+part|outside|out\s+of\s+scope)|`?barman-cloud`?.{0,120}(?:not\s+part|outside|out\s+of\s+scope)", "legacy in-image barman-cloud is excluded", "Keep legacy in-image backup tooling out of v1 scope.")
for forbidden in ["Alpine", "bullseye", "Artifact Hub"]:
    require(rf"{re.escape(forbidden)}.{{0,160}}out\s+of\s+scope|out\s+of\s+scope.{{0,160}}{re.escape(forbidden)}", f"{forbidden} is explicitly out of scope", "Document v1 exclusions clearly.")
reject(r"(?:Alpine|bullseye|Artifact Hub).{0,80}(?:in\s+scope|supported|published|included)", "forbidden platforms/metadata remain out of v1 scope", "Keep Alpine, bullseye, and Artifact Hub metadata out of scope.")
reject(r"PostgreSQL\s+`?(?:9|10|11|12|13|14|15|16)`?.{0,80}(?:in\s+scope|supported|published|included)", "legacy PostgreSQL majors remain out of v1 scope", "Only document 17, 18, and experimental 19beta1 for v1.")
reject(r"PostgreSQL\s+`?19(?:beta1)?`?.{0,80}(?:stable|production-ready|non-experimental)", "PostgreSQL 19 remains experimental", "Do not describe PG19 beta as stable or production-ready.")
reject_unless_negated(r"`latest`.{0,100}(?:points\s+to|targets|tracks|can\s+point\s+to|published\s+for|receives?|gets?|uses?|includes?|available\s+for).{0,100}(?:PostgreSQL\s+`?(?:17|19beta1)`?|Debian\s+`?bookworm`?)", "latest does not point to 17, 19beta1, or bookworm", "Keep latest targeting PostgreSQL 18 on Debian trixie only.")
reject(r"(?:primary\s+usage|primary\s+tag|primary\s+example).{0,80}`latest`|`latest`.{0,80}(?:primary\s+usage|primary\s+tag|primary\s+example)", "latest is not primary usage", "Use explicit PostgreSQL major tags as primary examples.")

expected = render_table(load_entries(metadata))
actual = table.read_text()
if actual != expected:
    fail(table, "compatibility table matches versions.yaml", actual[:1200], "Run make generate and commit the generated compatibility-table.md output.")
PY
}

validate_root_readme() {
  local readme="$1"
  python3 - "${readme}" <<'PY'
import re
import sys
from pathlib import Path

readme = Path(sys.argv[1])
command = f"validate-root-readme {readme}"

def fail(artifact, expected, actual, remediation):
    raise SystemExit(
        f"command: {command}\n"
        f"artifact: {artifact}\n"
        f"expected: {expected}\n"
        f"actual: {actual}\n"
        f"remediation: {remediation}"
    )

def require(pattern, expected, remediation, flags=re.I | re.S):
    if not re.search(pattern, text, flags):
        fail(readme, expected, "missing", remediation)

def reject(pattern, expected, remediation, flags=re.I | re.S):
    match = re.search(pattern, text, flags)
    if match:
        fail(readme, expected, match.group(0), remediation)

if not readme.exists():
    fail(readme, "root README artifact exists", "missing", "Keep a repository-level README for public navigation.")

text = readme.read_text()
require(r"#\s+pNet Containers", "root README names the repository, not one image family", "Use the root README as the repository entrypoint.")
require(r"container image sources", "root README explains repository purpose", "Describe the repository at a short overview level.")
require(r"Available Images", "root README has an available images section", "List supported image families without duplicating their full docs.")
require(r"CloudNativePG TimescaleDB", "root README lists the current image family", "Include the current image family in the catalog table.")
require(r"ghcr\.io/pnetcloud/cloudnative-pg-timescaledb", "root README documents the GHCR image namespace", "Show the registry users should pull from.")
require(r"cloudnative-pg-timescaledb/README\.md", "root README links to image-specific docs", "Send detailed image guidance to the image README.")
require(r"docs/README\.md", "root README links to the docs index", "Provide a docs navigation entry.")
require(r"CONTRIBUTING\.md", "root README links to contribution guidance", "Make contribution guidance discoverable.")
require(r"SECURITY\.md", "root README links to security reporting guidance", "Make security reporting guidance discoverable.")
require(r"make help", "root README exposes local command discovery", "Tell contributors how to find supported commands.")
reject(r"Manifest URL:\s+`https://github\.com/cloudnative-pg/plugin-barman-cloud", "root README does not duplicate generated Barman reference fields", "Keep generated Barman reference values in detailed docs.")
reject(r"Release:\s+`v\d+\.\d+\.\d+`", "root README does not duplicate generated release reference values", "Keep generated reference values out of the repository entrypoint.")
PY
}

expect_fail() {
  local fixture="$1"
  local pattern="$2"
  local table="${3:-${TABLE}}"
  local tmp status
  tmp="$(mktemp)"
  set +e
  validate_readme "${FIXTURE_DIR}/${fixture}" "${table}" >"${tmp}" 2>&1
  status="$?"
  set -e
  if [[ "${status}" == "0" ]]; then
    diag "validate-readme ${fixture}" "${FIXTURE_DIR}/${fixture}" "fixture fails" "passed" "Make the negative README fixture fail on its intended invariant."
    rm -f "${tmp}"
    exit 1
  fi
  if ! grep -E -q "${pattern}" "${tmp}"; then
    diag "validate-readme ${fixture}" "${FIXTURE_DIR}/${fixture}" "diagnostic matches ${pattern}" "$(tr '\n' ' ' <"${tmp}")" "Keep README diagnostics deterministic and actionable."
    rm -f "${tmp}"
    exit 1
  fi
  rm -f "${tmp}"
}

validate_root_readme "${ROOT_DIR}/README.md"
validate_readme "${ROOT_DIR}/cloudnative-pg-timescaledb/README.md"
validate_readme "${FIXTURE_DIR}/valid-readme.md"

expect_fail missing-trixie-primary.md "trixie is primary recommended"
expect_fail bookworm-not-secondary.md "bookworm is secondary"
expect_fail missing-pg19-experimental-warning.md "PostgreSQL 19beta1 is marked experimental"
expect_fail missing-latest-pg18-trixie.md "latest points to PostgreSQL 18 on Debian trixie"
expect_fail wrong-latest-target.md "latest does not point to 17, 19beta1, or bookworm|latest points to PostgreSQL 18 on Debian trixie"
expect_fail missing-barman-plugin-boundary.md "CloudNativePG Barman Cloud Plugin"
expect_fail legacy-barman-in-image-in-scope.md "legacy in-image barman-cloud is excluded|CloudNativePG Barman Cloud Plugin"
expect_fail alpine-in-scope.md "forbidden platforms/metadata remain out of v1 scope|Alpine is explicitly out of scope"
expect_fail bullseye-in-scope.md "forbidden platforms/metadata remain out of v1 scope|bullseye is explicitly out of scope"
expect_fail legacy-postgresql-in-scope.md "legacy PostgreSQL majors remain out of v1 scope"
expect_fail pg19-not-experimental.md "PostgreSQL 19 remains experimental|PostgreSQL 19beta1 is marked experimental"
expect_fail artifact-hub-in-scope.md "forbidden platforms/metadata remain out of v1 scope|Artifact Hub is explicitly out of scope"
tmp="$(mktemp)"
set +e
validate_readme "${FIXTURE_DIR}/valid-readme.md" "${FIXTURE_DIR}/stale-compatibility-table.md" >"${tmp}" 2>&1
status="$?"
set -e
if [[ "${status}" == "0" ]]; then
  diag "validate-readme stale compatibility table" "${FIXTURE_DIR}/stale-compatibility-table.md" "fixture fails" "passed" "Make stale generated compatibility tables fail README validation."
  rm -f "${tmp}"
  exit 1
fi
if ! grep -E -q "compatibility table matches versions.yaml" "${tmp}"; then
  diag "validate-readme stale compatibility table" "${FIXTURE_DIR}/stale-compatibility-table.md" "diagnostic matches compatibility table matches versions.yaml" "$(tr '\n' ' ' <"${tmp}")" "Report stale compatibility table drift directly."
  rm -f "${tmp}"
  exit 1
fi
rm -f "${tmp}"

printf 'PASS story-5.1 README compatibility docs fixtures\n'
